//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public int MaNL { get; set; }
        public int MaPhieuNhap { get; set; }
        public int SoLuong { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> DVT { get; set; }
    
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
