//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public int MaLoai { get; set; }
        public int MaNV { get; set; }
    
        public virtual LOAITK LOAITK { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
